# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlAppTmpl < Formula
  desc "A sitectl plugin template for application Compose stacks"
  homepage "https://github.com/libops/sitectl-app-tmpl"
  version "1.4.0"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v1.4.0/sitectl-app-tmpl_Darwin_x86_64.tar.gz"
      sha256 "fab26477d3a26861f8c707fe3888554949567c333c28ce9dbe95ab80a215aa17"

      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v1.4.0/sitectl-app-tmpl_Darwin_arm64.tar.gz"
      sha256 "5656e449202bd9d73859482262ea74c10a68e58a49fd6e8100a755b4f8408fde"

      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v1.4.0/sitectl-app-tmpl_Linux_x86_64.tar.gz"
      sha256 "57c1de3cfb43ee6c79f9e70eb6ab36736d6af3f3529d5baf8a8513bc779ec974"
      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v1.4.0/sitectl-app-tmpl_Linux_arm64.tar.gz"
      sha256 "f731eb8fd83f4efb9007ac0eaee2e1dad6c0c3b84664ef48db74d36ccd3783fb"
      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
  end
end
