# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlDrupal < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-drupal"
  version "0.4.0"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-drupal/releases/download/v0.4.0/sitectl-drupal_Darwin_x86_64.tar.gz"
      sha256 "14c6c295bb13a6a2974defdbb0e4a565fbe985d9dc221ed70c26f064bb86f6b2"

      define_method(:install) do
        bin.install "sitectl-drupal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-drupal/releases/download/v0.4.0/sitectl-drupal_Darwin_arm64.tar.gz"
      sha256 "7aa114bf54c7dce70e2900278e191fdcaa7ded9e994c7bd491f4bb58a437a5fd"

      define_method(:install) do
        bin.install "sitectl-drupal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-drupal/releases/download/v0.4.0/sitectl-drupal_Linux_x86_64.tar.gz"
      sha256 "82d15793e674a80fd48bac544dd25dc0cfac08e96223ff7b8ddb6995db62787e"
      define_method(:install) do
        bin.install "sitectl-drupal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-drupal/releases/download/v0.4.0/sitectl-drupal_Linux_arm64.tar.gz"
      sha256 "4617765ce4a061cdd0a51528c839074e4f6dc2c4970ed79e1331293885501361"
      define_method(:install) do
        bin.install "sitectl-drupal"
      end
    end
  end
end
