# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlAppTmpl < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-app-tmpl"
  version "0.1.2"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v0.1.2/sitectl-app-tmpl_Darwin_x86_64.tar.gz"
      sha256 "8eff7d4f4240467ed7f5322e688416dde4ba03c68d6a232ab955f8571699abe2"

      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v0.1.2/sitectl-app-tmpl_Darwin_arm64.tar.gz"
      sha256 "7446e09ec88d3ff291da33783088759abd85f56cffd30705d63a875da90a6961"

      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v0.1.2/sitectl-app-tmpl_Linux_x86_64.tar.gz"
      sha256 "18fc316f85245102880b03a28dc5c7830b1b0cd6163c8657d8a0da3be40604b3"
      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-app-tmpl/releases/download/v0.1.2/sitectl-app-tmpl_Linux_arm64.tar.gz"
      sha256 "a7fb5109c2d827d7be7296c5d369cf8d7fd4794fb7cdab6826a04b866f3411b3"
      define_method(:install) do
        bin.install "sitectl-app-tmpl"
      end
    end
  end
end
