# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlArchivesspace < Formula
  desc "A sitectl plugin for ArchivesSpace stacks"
  homepage "https://github.com/libops/sitectl-archivesspace"
  version "1.0.1"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v1.0.1/sitectl-archivesspace_Darwin_x86_64.tar.gz"
      sha256 "de5fa5a07b11a1e22d9d6a3ccd5bb5b0a9ea57f85250436c1f181654a19378bb"

      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v1.0.1/sitectl-archivesspace_Darwin_arm64.tar.gz"
      sha256 "589809b23309cac1f4cc34993a92f8dc21b181718a002a75538dfc5a6deca1b9"

      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v1.0.1/sitectl-archivesspace_Linux_x86_64.tar.gz"
      sha256 "9b3440b445b455273f9fb73d7f84d29b83b87b01aed496a58c6747ba5b808246"
      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v1.0.1/sitectl-archivesspace_Linux_arm64.tar.gz"
      sha256 "b15a29c82f74c8a97aa3fc4787d0c1a3475a921bfa4b4aa4ff53602b226f2dd1"
      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
  end
end
