# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlArchivesspace < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-archivesspace"
  version "0.3.0"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v0.3.0/sitectl-archivesspace_Darwin_x86_64.tar.gz"
      sha256 "b6959418ba2bde8a768fc222e805f4dccddd52b35bd8febe9e36dcaad1685575"

      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v0.3.0/sitectl-archivesspace_Darwin_arm64.tar.gz"
      sha256 "42691e5625a3f90306fe8bd847d4bf913e802fc317b010e7710493a2b45b633b"

      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v0.3.0/sitectl-archivesspace_Linux_x86_64.tar.gz"
      sha256 "1f556b4d89d8c9d45b323e394ceacb66f345e829d74f40263ac34c4553d59874"
      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-archivesspace/releases/download/v0.3.0/sitectl-archivesspace_Linux_arm64.tar.gz"
      sha256 "23963810bba2a10334170ab41a8a8d2c5b26e6eaadb4fbfe17e16bfb0a124d70"
      define_method(:install) do
        bin.install "sitectl-archivesspace"
      end
    end
  end
end
