# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlIsle < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-isle"
  version "0.8.1"

  depends_on "libops/homebrew/sitectl"
  depends_on "libops/homebrew/sitectl-drupal"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-isle/releases/download/v0.8.1/sitectl-isle_Darwin_x86_64.tar.gz"
      sha256 "cc2f9c43e44eb2d4776ac1547066e63bd757a3dba661b25f2947e42bfb1cefca"

      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-isle/releases/download/v0.8.1/sitectl-isle_Darwin_arm64.tar.gz"
      sha256 "2b0deac0593f5f4f1994f39b018333eb3a928372a3898c77814332f8f3b57b5f"

      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-isle/releases/download/v0.8.1/sitectl-isle_Linux_x86_64.tar.gz"
      sha256 "1532508bb62ef5a96c64dd84a88ad622f91a276d373d4d66adeea297951aa1ac"
      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-isle/releases/download/v0.8.1/sitectl-isle_Linux_arm64.tar.gz"
      sha256 "bbaa43e03f8be3ae910ea94e66ce4bb55eae6991dbb2329e8bb4d1b41c8cb7c7"
      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
  end
end
