# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlWp < Formula
  desc "A sitectl plugin for WordPress stacks"
  homepage "https://github.com/libops/sitectl-wp"
  version "1.2.1"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-wp/releases/download/v1.2.1/sitectl-wp_Darwin_x86_64.tar.gz"
      sha256 "1a58b6d451b163e7b7c9d849c9544957ec42f07ff410f74ef77c366aef2a55e9"

      define_method(:install) do
        bin.install "sitectl-wp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-wp/releases/download/v1.2.1/sitectl-wp_Darwin_arm64.tar.gz"
      sha256 "d4c5094d04b3c4a5d7ef33b9b0c3068366e3f2326d4ea6928a0c5242c98c5517"

      define_method(:install) do
        bin.install "sitectl-wp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-wp/releases/download/v1.2.1/sitectl-wp_Linux_x86_64.tar.gz"
      sha256 "60f2b0228af07c1b848a756334d7f845505b40b46644a7abf350da5b85f6ea7c"
      define_method(:install) do
        bin.install "sitectl-wp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-wp/releases/download/v1.2.1/sitectl-wp_Linux_arm64.tar.gz"
      sha256 "8ffbbb87c0ba0803fb06e0d35b2a55cfe92af86d9aaa0e34a41660195c351efb"
      define_method(:install) do
        bin.install "sitectl-wp"
      end
    end
  end
end
