# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlIsle < Formula
  desc "A sitectl plugin for Islandora stacks"
  homepage "https://github.com/libops/sitectl-isle"
  version "1.3.0"
  license "MIT"

  depends_on "libops/homebrew/sitectl"
  depends_on "libops/homebrew/sitectl-drupal"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-isle/releases/download/v1.3.0/sitectl-isle_Darwin_x86_64.tar.gz"
      sha256 "baf705f36d7cf078bfa23048c2324efe1091997bbca954904150eed5ff48f7f7"

      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-isle/releases/download/v1.3.0/sitectl-isle_Darwin_arm64.tar.gz"
      sha256 "d038d59bfb901ccad432a24657bd2f4ddf5e28b5bcf5ba204c7fdc2d7491b23a"

      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-isle/releases/download/v1.3.0/sitectl-isle_Linux_x86_64.tar.gz"
      sha256 "1ad0a34c3f6bf376e3c992189f26b29da5ae91d01cc863840f0c82ac89929ebe"
      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-isle/releases/download/v1.3.0/sitectl-isle_Linux_arm64.tar.gz"
      sha256 "a46246414b20e6c55ab0f3ed6488bc83ab4ee2dd084d81bf4a34974d8185abb3"
      define_method(:install) do
        bin.install "sitectl-isle"
      end
    end
  end
end
