# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlOmekaS < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-omeka-s"
  version "0.3.0"

  depends_on "libops/homebrew/sitectl"
  depends_on "libops/homebrew/sitectl-triplet"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.3.0/sitectl-omeka-s_Darwin_x86_64.tar.gz"
      sha256 "c3d3d3372743ee2cdc4b854ee9ab5d54b2001c4a2bbc5d7e486866fc45c36db0"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.3.0/sitectl-omeka-s_Darwin_arm64.tar.gz"
      sha256 "b86318595855a9b3223ce7f27fbc45d70f613ca963b14cfcdddcaced6f63c905"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.3.0/sitectl-omeka-s_Linux_x86_64.tar.gz"
      sha256 "e3512296ba600c8db37ed306391e9b3da285690d87104b99c5e443afbf0a503d"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.3.0/sitectl-omeka-s_Linux_arm64.tar.gz"
      sha256 "93ab3596f0ab14ac35675eedbbd70a36f35fb29befa9a6e360180aa5680b757e"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end
end
