# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sitectl < Formula
  desc ""
  homepage "https://github.com/libops/sitectl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl/releases/download/v0.1.0/sitectl_Darwin_x86_64.tar.gz"
      sha256 "d19d13fe8861545210caec9840f25a577c0e8ca3c5dcf7ae57ff0d4f682747a6"

      def install
        bin.install "sitectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl/releases/download/v0.1.0/sitectl_Darwin_arm64.tar.gz"
      sha256 "8639c0e804c43f4aa7b10d722a21f7f4e452b818dc999b949a2a6f575dbea14f"

      def install
        bin.install "sitectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl/releases/download/v0.1.0/sitectl_Linux_x86_64.tar.gz"
      sha256 "9d07ae49fcfe363d9506610c3cfdb3531f27b2cfc6c37fde810e4eae43de4b16"
      def install
        bin.install "sitectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl/releases/download/v0.1.0/sitectl_Linux_arm64.tar.gz"
      sha256 "924839f893e7262c2794ede2106e3e5d68136da5289ddd97738eb594df973c80"
      def install
        bin.install "sitectl"
      end
    end
  end
end
