# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sitectl < Formula
  desc ""
  homepage "https://github.com/libops/sitectl"
  version "0.29.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl/releases/download/v0.29.0/sitectl_Darwin_x86_64.tar.gz"
      sha256 "1b8bc43740f1ea235132b9b9edb48315a35e31c5cc86800f97ee4c446e2ccff1"

      define_method(:install) do
        bin.install "sitectl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl/releases/download/v0.29.0/sitectl_Darwin_arm64.tar.gz"
      sha256 "4d394bf8708d8ca61c63c6e0fb597b18d76b4d57ebb169cf2e21753c7f3cc9e5"

      define_method(:install) do
        bin.install "sitectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl/releases/download/v0.29.0/sitectl_Linux_x86_64.tar.gz"
      sha256 "df8eb83d450096884f24c7b5aee48ff9c6b86cc6a3efcccdc0c13e56ec5c51d5"
      define_method(:install) do
        bin.install "sitectl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl/releases/download/v0.29.0/sitectl_Linux_arm64.tar.gz"
      sha256 "758d1b65f552076f23a763501fdf0a74b2bb8bf696f0597a226be437d9d57003"
      define_method(:install) do
        bin.install "sitectl"
      end
    end
  end
end
