# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlOmekaClassic < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-omeka-classic"
  version "0.4.2"

  depends_on "libops/homebrew/sitectl"
  depends_on "libops/homebrew/sitectl-triplet"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-omeka-classic/releases/download/v0.4.2/sitectl-omeka-classic_Darwin_x86_64.tar.gz"
      sha256 "37e22bac986b5dce7fa6139aca7115522fe0f8a2c059da659da04b8d12ae18b8"

      define_method(:install) do
        bin.install "sitectl-omeka-classic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-omeka-classic/releases/download/v0.4.2/sitectl-omeka-classic_Darwin_arm64.tar.gz"
      sha256 "97d8ecc3f82c2abce927794f4657daa3eb1c62f4a806b4c5c328797d6d510b54"

      define_method(:install) do
        bin.install "sitectl-omeka-classic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-classic/releases/download/v0.4.2/sitectl-omeka-classic_Linux_x86_64.tar.gz"
      sha256 "7dd43f4479ab454f096b8cbeb66031c01481e0a361dbc906f1a71d06ddc47578"
      define_method(:install) do
        bin.install "sitectl-omeka-classic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-classic/releases/download/v0.4.2/sitectl-omeka-classic_Linux_arm64.tar.gz"
      sha256 "5e06ac03168019a3d64ef0528306a8fcd534bc7750aa9dc7eb011c533bec41a8"
      define_method(:install) do
        bin.install "sitectl-omeka-classic"
      end
    end
  end
end
