# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlOmekaS < Formula
  desc ""
  homepage "https://github.com/libops/sitectl-omeka-s"
  version "0.1.0"

  depends_on "libops/homebrew/sitectl"
  depends_on "libops/homebrew/sitectl-triplet"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.1.0/sitectl-omeka-s_Darwin_x86_64.tar.gz"
      sha256 "234ca3e1d0010a249410ac7b5b9b41cd9a404ce6ba58b2c626b135e99220afeb"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.1.0/sitectl-omeka-s_Darwin_arm64.tar.gz"
      sha256 "ea80863221649c8de5c8431b5e9751884ec44ae3f1dcaeeb057d7af8dfffa719"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.1.0/sitectl-omeka-s_Linux_x86_64.tar.gz"
      sha256 "c8705c592170988c42d293b333dd3805e71e4b036a5735990d11825780b3af69"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v0.1.0/sitectl-omeka-s_Linux_arm64.tar.gz"
      sha256 "929452090aa7436d04016e42038c7aad1e0e5212cd3a0ddba8e02c1ea40818c9"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end
end
