# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlLibops < Formula
  desc "A sitectl plugin for LibOps platform operations"
  homepage "https://github.com/libops/sitectl-libops"
  version "1.6.0"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.6.0/sitectl-libops_Darwin_x86_64.tar.gz"
      sha256 "5e68db0d3d4ecbb7b493d2f0d5c930212e47640acae9c0c83a26085fda9cddd3"

      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.6.0/sitectl-libops_Darwin_arm64.tar.gz"
      sha256 "2b20d53b9466342baafa1f6ec42a53575c58a4bec53db297affc40671c1d541b"

      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.6.0/sitectl-libops_Linux_x86_64.tar.gz"
      sha256 "4213964a0662129723dfae1bcf1eceb76308fd0a92ac0b686dd4568171be1f18"
      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.6.0/sitectl-libops_Linux_arm64.tar.gz"
      sha256 "3af8249a0361a86194aaf0db5e97dab9e389d1087c909b1adc43b4974d8e514e"
      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
  end
end
