# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlLibops < Formula
  desc "A sitectl plugin for LibOps platform operations"
  homepage "https://github.com/libops/sitectl-libops"
  version "1.7.1"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.7.1/sitectl-libops_Darwin_x86_64.tar.gz"
      sha256 "cdac5ce6d107cf84559a942dcb83edbd9f2a63342383d125fc62a5b2e2aa9426"

      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.7.1/sitectl-libops_Darwin_arm64.tar.gz"
      sha256 "83a91423daf5882b1992fab3628a08b0bbcfb7d3a966b968cf0397e4554750d6"

      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.7.1/sitectl-libops_Linux_x86_64.tar.gz"
      sha256 "6c13f48bdf3eb683a05644da3fc0941563fbf42a217dc9bf20d8a54ce3546439"
      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-libops/releases/download/v1.7.1/sitectl-libops_Linux_arm64.tar.gz"
      sha256 "71782de92316fd1eb4f6fcd2ac9fbc0418151bccac810e7b50c56d15934253fa"
      define_method(:install) do
        bin.install "sitectl-libops"
      end
    end
  end
end
