# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SitectlOmekaS < Formula
  desc "A sitectl plugin for Omeka S stacks"
  homepage "https://github.com/libops/sitectl-omeka-s"
  version "1.1.0"
  license "MIT"

  depends_on "libops/homebrew/sitectl"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v1.1.0/sitectl-omeka-s_Darwin_x86_64.tar.gz"
      sha256 "f8f391859c86bb88277f88987599e319d8557a03d8217d56801bf7cd0b0ef3cd"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v1.1.0/sitectl-omeka-s_Darwin_arm64.tar.gz"
      sha256 "e47efe085c228c9684b01f81f73e27aa525193fc052e416b22c144a52041eb89"

      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v1.1.0/sitectl-omeka-s_Linux_x86_64.tar.gz"
      sha256 "d1ac2c2a34bff298440249d8045645846573d0be6005e21fb172bd3664d02fbf"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/libops/sitectl-omeka-s/releases/download/v1.1.0/sitectl-omeka-s_Linux_arm64.tar.gz"
      sha256 "c76fe100b4b076cfdebc36539c6f976197ffdbb650f8ca9486e5aa7b46bc6edc"
      define_method(:install) do
        bin.install "sitectl-omeka-s"
      end
    end
  end
end
